-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Мар 03 2019 г., 02:07
-- Версия сервера: 5.6.41
-- Версия PHP: 7.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `gbphp`
--

-- --------------------------------------------------------

--
-- Структура таблицы `items`
--

CREATE TABLE `items` (
  `id` int(11) NOT NULL,
  `name` text NOT NULL,
  `img-min` text NOT NULL,
  `img-max` text NOT NULL,
  `about` text NOT NULL,
  `price` double NOT NULL,
  `type` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `items`
--

INSERT INTO `items` (`id`, `name`, `img-min`, `img-max`, `about`, `price`, `type`) VALUES
(1, 'Mango People T-shirt 1', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(2, 'Mango People T-shirt 2', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(3, 'Mango People T-shirt 3', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(4, 'Mango People T-shirt 4', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(5, 'Mango People T-shirt 5', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(6, 'Mango People T-shirt 6', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(7, 'Mango People T-shirt 7', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(8, 'Mango People T-shirt 8', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(9, 'Mango People T-shirt 9', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(10, 'Mango People T-shirt 10', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(11, 'Mango People T-shirt 11', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(12, 'Mango People T-shirt 12', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(13, 'Mango People T-shirt 13', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(14, 'Mango People T-shirt 14', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(15, 'Mango People T-shirt 15', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(16, 'Mango People T-shirt 16', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(17, 'Mango People T-shirt 17', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(18, 'Mango People T-shirt 18', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(19, 'Mango People T-shirt 19', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(20, 'Mango People T-shirt 20', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(21, 'Mango People T-shirt 21', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(22, 'Mango People T-shirt 22', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(23, 'Mango People T-shirt 23', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(24, 'Mango People T-shirt 24', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(25, 'Mango People T-shirt 25', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(26, 'Mango People T-shirt 26', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(27, 'Mango People T-shirt 27', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(28, 'Mango People T-shirt 28', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(29, 'Mango People T-shirt 29', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(30, 'Mango People T-shirt 30', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(31, 'Mango People T-shirt 31', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(32, 'Mango People T-shirt 32', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(33, 'Mango People T-shirt 33', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(34, 'Mango People T-shirt 34', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(35, 'Mango People T-shirt 35', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(36, 'Mango People T-shirt 36', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(37, 'Mango People T-shirt 37', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(38, 'Mango People T-shirt 38', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(39, 'Mango People T-shirt 39', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(40, 'Mango People T-shirt 40', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(41, 'Mango People T-shirt 41', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(42, 'Mango People T-shirt 42', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(43, 'Mango People T-shirt 43', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(44, 'Mango People T-shirt 44', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(45, 'Mango People T-shirt 45', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(46, 'Mango People T-shirt 46', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(47, 'Mango People T-shirt 47', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(48, 'Mango People T-shirt 48', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(49, 'Mango People T-shirt 49', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(50, 'Mango People T-shirt 50', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(51, 'Mango People T-shirt 51', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(52, 'Mango People T-shirt 52', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(53, 'Mango People T-shirt 53', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(54, 'Mango People T-shirt 54', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(55, 'Mango People T-shirt 55', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(56, 'Mango People T-shirt 56', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(57, 'Mango People T-shirt 57', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(58, 'Mango People T-shirt 58', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(59, 'Mango People T-shirt 59', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(60, 'Mango People T-shirt 60', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(61, 'Mango People T-shirt 61', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(62, 'Mango People T-shirt 62', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(63, 'Mango People T-shirt 63', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(64, 'Mango People T-shirt 64', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(65, 'Mango People T-shirt 65', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(66, 'Mango People T-shirt 66', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(67, 'Mango People T-shirt 67', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(68, 'Mango People T-shirt 68', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(69, 'Mango People T-shirt 69', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(70, 'Mango People T-shirt 70', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(71, 'Mango People T-shirt 71', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(72, 'Mango People T-shirt 72', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(73, 'Mango People T-shirt 73', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(74, 'Mango People T-shirt 74', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(75, 'Mango People T-shirt 75', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(76, 'Mango People T-shirt 76', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(77, 'Mango People T-shirt 77', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(78, 'Mango People T-shirt 78', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(79, 'Mango People T-shirt 79', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(80, 'Mango People T-shirt 80', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(81, 'Mango People T-shirt 81', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(82, 'Mango People T-shirt 82', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(83, 'Mango People T-shirt 83', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(84, 'Mango People T-shirt 84', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(85, 'Mango People T-shirt 85', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(86, 'Mango People T-shirt 86', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(87, 'Mango People T-shirt 87', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(88, 'Mango People T-shirt 88', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(89, 'Mango People T-shirt 89', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(90, 'Mango People T-shirt 90', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(91, 'Mango People T-shirt 91', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(92, 'Mango People T-shirt 92', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(93, 'Mango People T-shirt 93', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(94, 'Mango People T-shirt 94', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(95, 'Mango People T-shirt 95', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(96, 'Mango People T-shirt 96', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6),
(97, 'Mango People T-shirt 97', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.49, 6),
(98, 'Mango People T-shirt 98', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(99, 'Mango People T-shirt 99', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(100, 'Mango People T-shirt 100', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 3.99, 6),
(101, 'Mango People T-shirt 101', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.99, 6),
(102, 'Mango People T-shirt 102', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.49, 6),
(103, 'Mango People T-shirt 103', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.29, 6),
(104, 'Mango People T-shirt 104', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 4.99, 6),
(105, 'Mango People T-shirt 105', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 6.49, 6),
(106, 'Mango People T-shirt 106', 'http://placehold.it/260x220', 'http://placehold.it/360x400', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At delectus, doloremque enim ex natus perferendis repellendus sequi voluptates! Consectetur consequatur fuga iste nostrum! Accusantium, impedit, veritatis! Accusantium quasi quisquam ullam.', 5.99, 6);

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `items`
--
ALTER TABLE `items`
  ADD UNIQUE KEY `id` (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `items`
--
ALTER TABLE `items`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=107;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
